#!/bin/bash

./process.py outputs/hw4/LRU/blackscholes_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/bodytrack_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/bzip2/zsim.out
./process.py outputs/hw4/LRU/cactusADM/zsim.out
./process.py outputs/hw4/LRU/calculix/zsim.out
./process.py outputs/hw4/LRU/canneal_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/dedup_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/fluidanimate_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/freqmine_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/gcc/zsim.out
./process.py outputs/hw4/LRU/hmmer/zsim.out
./process.py outputs/hw4/LRU/lbm/zsim.out
./process.py outputs/hw4/LRU/leslie3d/zsim.out
./process.py outputs/hw4/LRU/libquantum/zsim.out
./process.py outputs/hw4/LRU/mcf/zsim.out
./process.py outputs/hw4/LRU/milc/zsim.out
./process.py outputs/hw4/LRU/namd/zsim.out
./process.py outputs/hw4/LRU/sjeng/zsim.out
./process.py outputs/hw4/LRU/soplex/zsim.out
./process.py outputs/hw4/LRU/streamcluster_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/swaptions_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/x264_8c_simlarge/zsim.out
./process.py outputs/hw4/LRU/xalan/zsim.out

./process.py outputs/hw4/LFU/blackscholes_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/bodytrack_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/bzip2/zsim.out
./process.py outputs/hw4/LFU/cactusADM/zsim.out
./process.py outputs/hw4/LFU/calculix/zsim.out
./process.py outputs/hw4/LFU/canneal_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/dedup_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/fluidanimate_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/freqmine_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/gcc/zsim.out
./process.py outputs/hw4/LFU/hmmer/zsim.out
./process.py outputs/hw4/LFU/lbm/zsim.out
./process.py outputs/hw4/LFU/leslie3d/zsim.out
./process.py outputs/hw4/LFU/libquantum/zsim.out
./process.py outputs/hw4/LFU/mcf/zsim.out
./process.py outputs/hw4/LFU/milc/zsim.out
./process.py outputs/hw4/LFU/namd/zsim.out
./process.py outputs/hw4/LFU/sjeng/zsim.out
./process.py outputs/hw4/LFU/soplex/zsim.out
./process.py outputs/hw4/LFU/streamcluster_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/swaptions_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/x264_8c_simlarge/zsim.out
./process.py outputs/hw4/LFU/xalan/zsim.out

./process.py outputs/hw4/SRRIP/blackscholes_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/bodytrack_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/bzip2/zsim.out
./process.py outputs/hw4/SRRIP/cactusADM/zsim.out
./process.py outputs/hw4/SRRIP/calculix/zsim.out
./process.py outputs/hw4/SRRIP/canneal_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/dedup_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/fluidanimate_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/freqmine_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/gcc/zsim.out
./process.py outputs/hw4/SRRIP/hmmer/zsim.out
./process.py outputs/hw4/SRRIP/lbm/zsim.out
./process.py outputs/hw4/SRRIP/leslie3d/zsim.out
./process.py outputs/hw4/SRRIP/libquantum/zsim.out
./process.py outputs/hw4/SRRIP/mcf/zsim.out
./process.py outputs/hw4/SRRIP/milc/zsim.out
./process.py outputs/hw4/SRRIP/namd/zsim.out
./process.py outputs/hw4/SRRIP/sjeng/zsim.out
./process.py outputs/hw4/SRRIP/soplex/zsim.out
./process.py outputs/hw4/SRRIP/streamcluster_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/swaptions_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/x264_8c_simlarge/zsim.out
./process.py outputs/hw4/SRRIP/xalan/zsim.out

